name: Bump version

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.action_token }}
